#!/usr/bin/env python
# encoding: utf-8
"""
ask

Created by Max Hodak on 2009-10-11.
Copyright (c) 2009 Max Hodak. All rights reserved.
"""

import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
  s.connect(('maxhodak.com',11911))
  s.send('<ask>')
  data = s.recv(1024)
  s.close()
  print data
except:
  print "Something went wrong; maybe the server is temporarily down?"