#!/usr/bin/env python
# encoding: utf-8
"""
tell

Created by Max Hodak on 2009-10-11.
Copyright (c) 2009 Max Hodak. All rights reserved.
"""

import socket, sys

try:
  s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  s.connect(('maxhodak.com',11911))
  s.send(sys.argv[1])
  data = s.recv(1024)
  if data != 'true':
    print "An error occurred: you message wasn't sent."
  s.close()
except:
  print "Something went wrong; maybe the server is temporarily down?"